(function(){
'use strict';
document.documentElement.classList.add('mff-auth-pending');
const KEY='mff_admin_session_v1';
const css=`html.mff-auth-pending body>*:not(#mff-login-root){visibility:hidden!important}html.mff-auth-pending #mff-login-root{visibility:visible!important}#mff-login-root{position:fixed;inset:0;z-index:2147483000;display:flex;align-items:center;justify-content:center;padding:18px;background:radial-gradient(ellipse at top,#e9f2f5 0%,#f5f7fa 48%,#e8edf2 100%);font-family:system-ui,-apple-system,'Segoe UI',sans-serif;color:#142b40}#mff-login-root *{box-sizing:border-box}#mff-login-card{width:min(100%,370px);border:1px solid #ffffffd9;border-radius:30px;padding:28px 24px 24px;background:#ffffffed;box-shadow:0 24px 70px #18354b1b;text-align:center}#mff-login-mark{width:70px;height:70px;margin:0 auto 15px;border-radius:23px;background:linear-gradient(145deg,#e7f1f4,#dce7ec);display:grid;place-items:center;font-size:31px;box-shadow:inset 0 1px #fff,0 7px 18px #17364b13}#mff-login-card h1{font-size:23px;letter-spacing:-.5px;margin:0;font-weight:750}#mff-login-sub{font-size:13px;color:#84929d;margin:5px 0 21px}#mff-login-user{width:100%;height:46px;border:1px solid #dce4e8;border-radius:14px;padding:0 14px;font-size:15px;background:#f9fbfc;color:#20384b;outline:none;margin-bottom:18px}#mff-login-user:focus{border-color:#7899aa;box-shadow:0 0 0 3px #dceaf0}#mff-pin-dots{display:flex;justify-content:center;gap:13px;margin:0 0 22px}#mff-pin-dots i{width:12px;height:12px;border-radius:50%;border:1.6px solid #9baeb9;background:transparent;transition:.12s}#mff-pin-dots i.filled{background:#173b55;border-color:#173b55;transform:scale(1.05)}#mff-keypad{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;max-width:280px;margin:auto}#mff-keypad button{border:1px solid #edf1f3;border-radius:17px;background:linear-gradient(180deg,#fff,#f7f9fa);height:57px;color:#18364c;font-size:23px;font-weight:600;box-shadow:0 3px 8px #1c34450a;cursor:pointer;touch-action:manipulation}#mff-keypad button:active{transform:scale(.96);background:#eaf1f4}#mff-keypad button.alt{font-size:13px;font-weight:650;color:#7c8b96}#mff-login-submit{width:100%;height:48px;border:0;border-radius:15px;margin-top:17px;background:linear-gradient(135deg,#173b55,#245a75);color:white;font-size:15px;font-weight:700;box-shadow:0 7px 17px #173b5526;cursor:pointer}#mff-login-submit:disabled{opacity:.42;box-shadow:none}#mff-login-error{min-height:20px;margin:11px 0 0;color:#bd5360;font-size:12px}#mff-login-lock{font-size:11px;color:#a0abb3;margin-top:14px}body.mff-login-locked{overflow:hidden}`;
function endpoint(){return window.MFF_ENDPOINT||''}
function request(action,data){return fetch(endpoint(),{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(Object.assign({action},data||{}))}).then(r=>r.json())}
function read(){try{return JSON.parse(sessionStorage.getItem(KEY)||'null')}catch(e){return null}}
function write(v){sessionStorage.setItem(KEY,JSON.stringify(v));sessionStorage.setItem('mff_auth_token',v.token)}
function clear(){sessionStorage.removeItem(KEY);sessionStorage.removeItem('mff_auth_token')}
function install(){if(document.getElementById('mff-login-root'))return;const style=document.createElement('style');style.textContent=css;document.head.appendChild(style);const root=document.createElement('div');root.id='mff-login-root';root.innerHTML=`<section id="mff-login-card" role="dialog" aria-modal="true" aria-labelledby="mff-login-title"><div id="mff-login-mark">🔐</div><h1 id="mff-login-title">My Family Funds</h1><div id="mff-login-sub">เข้าสู่ระบบผู้ดูแล · Admin Access</div><input id="mff-login-user" autocomplete="username" value="admin" aria-label="ชื่อผู้ใช้" placeholder="ชื่อผู้ใช้"><div id="mff-pin-dots" aria-label="รหัส PIN 6 หลัก">${'<i></i>'.repeat(6)}</div><div id="mff-keypad">${['1','2','3','4','5','6','7','8','9','clear','0','back'].map(x=>`<button type="button" class="${/clear|back/.test(x)?'alt':''}" data-key="${x}">${x==='clear'?'ล้าง':x==='back'?'⌫':x}</button>`).join('')}</div><button id="mff-login-submit" disabled type="button">ยืนยันการเข้าสู่ระบบ</button><div id="mff-login-error" role="status"></div><div id="mff-login-lock">◈ PIN 6 หลัก · เซสชัน 12 ชั่วโมง</div></section>`;document.body.appendChild(root);document.body.classList.add('mff-login-locked');let pin='';const dots=[...root.querySelectorAll('#mff-pin-dots i')],submit=root.querySelector('#mff-login-submit'),error=root.querySelector('#mff-login-error');function paint(){dots.forEach((d,i)=>d.classList.toggle('filled',i<pin.length));submit.disabled=pin.length!==6;error.textContent=''}function add(v){if(pin.length<6&&/^\d$/.test(v)){pin+=v;paint();if(pin.length===6)submit.focus()}}root.querySelector('#mff-keypad').addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;const k=b.dataset.key;if(k==='clear')pin='';else if(k==='back')pin=pin.slice(0,-1);else add(k);paint()});root.querySelector('#mff-login-user').addEventListener('keydown',e=>{if(e.key==='Enter')root.querySelector('#mff-keypad button[data-key="1"]').focus()});submit.addEventListener('click',async()=>{if(pin.length!==6)return;submit.disabled=true;submit.textContent='กำลังตรวจสอบ…';error.textContent='';try{const r=await request('adminLogin',{username:root.querySelector('#mff-login-user').value.trim(),pin});if(r.ok&&r.token){write({token:r.token,username:r.username,expiresAt:r.expiresAt});root.remove();document.body.classList.remove('mff-login-locked');location.reload();return}error.textContent=r.error||'เข้าสู่ระบบไม่สำเร็จ';}catch(e){error.textContent='เชื่อมต่อระบบยืนยันไม่ได้ กรุณาตรวจสอบ Apps Script และ Deploy';}pin='';paint();submit.textContent='ยืนยันการเข้าสู่ระบบ';});paint()}
async function boot(){const s=read();if(s&&s.token&&s.expiresAt>Date.now()){try{const r=await request('validateAdminSession',{token:s.token});if(r.ok&&r.authenticated){document.documentElement.classList.remove('mff-auth-pending');addLogout(s);return;} }catch(e){/* show login if backend cannot validate */}clear()}install();document.documentElement.classList.remove('mff-auth-pending')}
function addLogout(s){if(document.getElementById('mff-logout-chip'))return;const b=document.createElement('button');b.id='mff-logout-chip';b.type='button';b.title='ออกจากระบบ';b.setAttribute('aria-label','ออกจากระบบ');b.textContent='ออกจากระบบ';b.style.cssText='position:fixed;right:10px;top:10px;z-index:99999;border:1px solid #d9e3e8;background:#fff;color:#385064;border-radius:12px;padding:7px 10px;font:600 11px system-ui;opacity:.82';b.addEventListener('click',async()=>{try{await request('adminLogout',{token:s.token})}catch(e){}clear();location.reload()});document.body.appendChild(b)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
